name: cluves
description: Cluves - be closer to your favourite brands

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  font_awesome_flutter: ^10.1.0
  syncfusion_flutter_datepicker: ^20.2.48
  flutter_bloc: ^8.1.1
  connectivity_plus: ^2.3.6+1
  equatable: ^2.0.5
  formz: ^0.4.1
  intl: ^0.17.0
  dio: ^4.0.6
  splashscreen: ^1.3.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_svg: ^1.1.5
  expandable_text: ^2.3.0
  simple_shadow: ^0.3.0
  qr_flutter: ^4.0.0
  share: ^2.0.4
  path_provider: ^2.0.11
  screenshot: ^1.2.3
  flutter_secure_storage: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  hive_generator: ^1.1.3
  build_runner: ^2.2.1
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/CluvsLogo.jpg"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/icons/Navigation/

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa/static/Comfortaa-Bold.ttf
          weight: 700
        - asset: assets/fonts/Comfortaa/static/Comfortaa-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Comfortaa/static/Comfortaa-Medium.ttf
          weight: 500
        - asset: assets/fonts/Comfortaa/static/Comfortaa-Regular.ttf
          weight: 400
        - asset: assets/fonts/Comfortaa/static/Comfortaa-Light.ttf
          weight: 300
